rpc_url: "https://rpc.testnet.fluence.dev"
graph_node_url: 'https://graph-node.stage.fluence.dev/subgraphs/name/fluence-deal-contracts-3d15b6b4'

addresses:
  - address: "0x9262768725134b7d52041FAb42287EA2147D0c77"
    name: foobar
    minimum_balance: 100000000

providers:
  - "0x957b816cab1b9e429c3282c8f389f1fd2f8cfe1a"
